# Numpy for Data Science

[Numpy](https://numpy.org/) is a Linear Algebra Library for Python . Numpy as one of the main building blocks in the PyData Ecosystem.

We use Numpy to work with arrays in python.
Numpy provides a high-performance multidimensional array object and tools for working with these arrays .

# Creating Numpy array using List 

In [1]:
list = [1,2,3]

In [2]:
list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(list)

array([1, 2, 3])

# Note 
Numpy arrays have vectors and matrices :
Vectors are  1-d arrays and matrices are 2-d arrays.

In [5]:
# 2d array

matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange function 
arange((start), (stop), (step), dtype=None, *, like=None)

Return evenly spaced values within a given interval.

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

# zeros/ones function
return the array of 0's/1's 

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
#(single row)
#((rows,columns))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace() function

Return evenly spaced numbers over a specified interval.
(start , stop , in_between_points)

In [12]:
np.linspace(3,5,6)

array([3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [13]:
#indentity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random Module

Python provides a built-in module called random for generation random numbers 

In [14]:
#random.randn(n): This function generates a 'n' random floating-point number between 0.0 (inclusive) and 1.0 (exclusive).

In [15]:
np.random.rand(10)

array([0.34838689, 0.77307449, 0.79296988, 0.79423159, 0.81627294,
       0.86276761, 0.4927361 , 0.06445344, 0.02138307, 0.49538402])

In [16]:
#random.randn() : Generates random samples from the standard normal distribution (also called the Gaussian distribution).
#This distribution has a mean of 0 and a variance of 1.

In [17]:
np.random.randn(5)

array([-2.12367877,  0.31703982, -1.30075373,  0.12109605,  0.22058721])

In [18]:
#random.randint(a, b): Generates a random integer between two integers (a and b)

In [19]:
np.random.randint(6,10)

8

In [20]:
np.random.randint(1,50,6)

array([ 2, 33, 48, 37,  5, 24])